// ទុកសម្រាប់ផ្ទុកទិន្នន័យរូបភាព និងវីដេអូទាំងអស់
const allMedia = [
        { type: "image", src: "Image/1.jfif", alt: "Art 1" },
        { type: "video", src: "Video/1.mp4", alt: "Video 1" },
        { type: "image", src: "Image/2.jfif", alt: "Art 2" },
        { type: "video", src: "Video/2.mp4", alt: "Video 2" },
        { type: "image", src: "Image/3.jfif", alt: "Art 3" },
        { type: "video", src: "Video/3.mp4", alt: "Video 3" },
        { type: "video", src: "Video/4.mp4", alt: "Video 4" },
        { type: "image", src: "Image/4.jpg", alt: "Art 4" },
        { type: "image", src: "Image/5.jpg", alt: "Art 5" },
        { type: "image", src: "Image/6.jpg", alt: "Art 6" },
        { type: "image", src: "Image/7.jpg", alt: "Art 7" },
        { type: "image", src: "Image/8.jfif", alt: "Art 8" },
        { type: "image", src: "Image/9.jfif", alt: "Art 9" },
        { type: "image", src: "Image/10.jfif", alt: "Art 10" },
        { type: "image", src: "Image/11.jfif", alt: "Art 11" },
        { type: "image", src: "Image/12.jpg", alt: "Art 12" },
        { type: "image", src: "Image/13.jpg", alt: "Art 13" },
        { type: "image", src: "Image/14.jpg", alt: "Art 14" },
        { type: "image", src: "Image/15.jpg", alt: "Art 15" },
        { type: "image", src: "Image/16.jpg", alt: "Art 16" },
        { type: "image", src: "Image/17.jpg", alt: "Art 17" },
        { type: "image", src: "Image/18.jpg", alt: "Art 18" },
        { type: "image", src: "Image/19.jpg", alt: "Art 19" },
        { type: "image", src: "Image/20.jpg", alt: "Art 20" },
        { type: "image", src: "Image/21.jpg", alt: "Art 21" },
        { type: "image", src: "Image/22.jpg", alt: "Art 22" },
        { type: "image", src: "Image/23.jpg", alt: "Art 23" },
        { type: "image", src: "Image/24.jpg", alt: "Art 24" },
        { type: "image", src: "Image/25.jpg", alt: "Art 25" },
        { type: "image", src: "Image/26.jpg", alt: "Art 26" },
        { type: "image", src: "Image/27.jpg", alt: "Art 27" },
        { type: "image", src: "Image/28.jpg", alt: "Art 28" },
        { type: "image", src: "Image/29.jpg", alt: "Art 29" },
        { type: "image", src: "Image/30.jpg", alt: "Art 30" },
        { type: "image", src: "Image/31.jpg", alt: "Art 31" },
        { type: "image", src: "Image/32.jpg", alt: "Art 32" },
        { type: "image", src: "Image/33.jpg", alt: "Art 33" },
        { type: "image", src: "Image/34.jpg", alt: "Art 34" },
        { type: "image", src: "Image/35.jpg", alt: "Art 35" },
        { type: "image", src: "Image/36.jpg", alt: "Art 36" },
        { type: "image", src: "Image/37.jpg", alt: "Art 37" },
        { type: "image", src: "Image/38.jpg", alt: "Art 38" },
        { type: "image", src: "Image/39.jpg", alt: "Art 39" },
        { type: "image", src: "Image/40.jpg", alt: "Art 40" },
        { type: "image", src: "Image/41.jpg", alt: "Art 41" },
        { type: "image", src: "Image/42.jpg", alt: "Art 42" },
        { type: "image", src: "Image/43.jpg", alt: "Art 43" },
        { type: "image", src: "Image/44.jpg", alt: "Art 44" },
        { type: "image", src: "Image/45.jpg", alt: "Art 45" },
        { type: "image", src: "Image/46.jpg", alt: "Art 46" },
        { type: "image", src: "Image/47.jpg", alt: "Art 47" },
        { type: "image", src: "Image/48.jpg", alt: "Art 48" },
        { type: "image", src: "Image/49.jpg", alt: "Art 49" },
        { type: "image", src: "Image/50.jpg", alt: "Art 50" },
        { type: "image", src: "Image/51.jpg", alt: "Art 51" },
        { type: "image", src: "Image/52.jpg", alt: "Art 52" },
        { type: "image", src: "Image/53.jpg", alt: "Art 53" },
        { type: "image", src: "Image/54.jpg", alt: "Art 54" },
        { type: "image", src: "Image/55.jpg", alt: "Art 55" },
        { type: "image", src: "Image/56.jpg", alt: "Art 56" },
        { type: "image", src: "Image/57.jpg", alt: "Art 57" },
        { type: "image", src: "Image/58.jpg", alt: "Art 58" },
        { type: "image", src: "Image/59.jpg", alt: "Art 59" },
        { type: "image", src: "Image/60.jpg", alt: "Art 60" },
        { type: "image", src: "Image/61.jpg", alt: "Art 61" },
        { type: "image", src: "Image/62.jpg", alt: "Art 62" },
        { type: "image", src: "Image/63.jpg", alt: "Art 63" },
        { type: "image", src: "Image/64.jpg", alt: "Art 64" },
        { type: "image", src: "Image/65.jpg", alt: "Art 65" },
        { type: "image", src: "Image/66.jpg", alt: "Art 66" },
        { type: "image", src: "Image/67.jpg", alt: "Art 67" },
        { type: "image", src: "Image/68.jpg", alt: "Art 68" },
        { type: "image", src: "Image/69.jpg", alt: "Art 69" },
        { type: "image", src: "Image/70.jpg", alt: "Art 70" },
        { type: "image", src: "Image/71.jpg", alt: "Art 71" },
        { type: "image", src: "Image/72.jpg", alt: "Art 72" },
        { type: "image", src: "Image/73.jpg", alt: "Art 73" },
        { type: "image", src: "Image/74.jpg", alt: "Art 74" },
        { type: "image", src: "Image/75.jpg", alt: "Art 75" },
        { type: "image", src: "Image/76.jpg", alt: "Art 76" },
        { type: "image", src: "Image/77.jpg", alt: "Art 77" },
        { type: "image", src: "Image/78.jpg", alt: "Art 78" },
        { type: "image", src: "Image/79.jpg", alt: "Art 79" },
        { type: "image", src: "Image/80.jpg", alt: "Art 80" },
        { type: "image", src: "Image/81.jpg", alt: "Art 81" },
        { type: "image", src: "Image/82.jpg", alt: "Art 82" },
        { type: "image", src: "Image/83.jpg", alt: "Art 83" },
        { type: "image", src: "Image/84.jpg", alt: "Art 84" },
        { type: "image", src: "Image/85.jpg", alt: "Art 85" },
        { type: "image", src: "Image/86.jpg", alt: "Art 86" },
        { type: "image", src: "Image/87.jpg", alt: "Art 87" },
        { type: "image", src: "Image/88.jpg", alt: "Art 88" },
        { type: "image", src: "Image/89.jpg", alt: "Art 89" },
        { type: "image", src: "Image/90.jpg", alt: "Art 90" },
        { type: "image", src: "Image/91.jpg", alt: "Art 91" },
        { type: "image", src: "Image/92.jpg", alt: "Art 92" },
        { type: "image", src: "Image/93.jpg", alt: "Art 93" },
        { type: "image", src: "Image/94.jpg", alt: "Art 94" },
        { type: "image", src: "Image/95.jpg", alt: "Art 95" },
        { type: "image", src: "Image/96.jpg", alt: "Art 96" },
        { type: "image", src: "Image/97.jpg", alt: "Art 97" },
        { type: "image", src: "Image/98.jpg", alt: "Art 98" },
        { type: "image", src: "Image/99.jpg", alt: "Art 99" },
        { type: "image", src: "Image/100.jpg", alt: "Art 100" },
        { type: "image", src: "Image/101.jpg", alt: "Art 101" },
        { type: "image", src: "Image/102.jpg", alt: "Art 102" },
        { type: "video", src: "Video/5.mp4", alt: "Video 5" },
        { type: "video", src: "Video/6.mp4", alt: "Video 6" },
        { type: "image", src: "Image/103.jpg", alt: "Art 103" },
        { type: "image", src: "Image/104.jpg", alt: "Art 104" },
        { type: "image", src: "Image/105.jpg", alt: "Art 105" },
        { type: "image", src: "Image/106.jpg", alt: "Art 106" },
        { type: "image", src: "Image/107.jpg", alt: "Art 107" },
        { type: "image", src: "Image/108.jpg", alt: "Art 108" },
        { type: "image", src: "Image/109.jpg", alt: "Art 109" },
        { type: "image", src: "Image/110.jpg", alt: "Art 110" },
        { type: "image", src: "Image/111.jpg", alt: "Art 111" },
        { type: "image", src: "Image/112.jpg", alt: "Art 112" },
        { type: "image", src: "Image/113.jpg", alt: "Art 113" },
        { type: "image", src: "Image/114.jpg", alt: "Art 114" },
        { type: "image", src: "Image/115.jpg", alt: "Art 115" },
        { type: "image", src: "Image/116.jpg", alt: "Art 116" },
        { type: "image", src: "Image/117.jpg", alt: "Art 117" },
        { type: "image", src: "Image/118.jpg", alt: "Art 118" },
        { type: "image", src: "Image/119.jpg", alt: "Art 119" },
        { type: "image", src: "Image/200.jpg", alt: "Art 200" },
        { type: "image", src: "Image/201.jpg", alt: "Art 201" },
        { type: "image", src: "Image/202.jpg", alt: "Art 202" },
        { type: "image", src: "Image/203.jpg", alt: "Art 203" },
        { type: "image", src: "Image/204.jpg", alt: "Art 204" },
        { type: "image", src: "Image/205.jpg", alt: "Art 205" },
        { type: "image", src: "Image/206.jpg", alt: "Art 206" },
        { type: "image", src: "Image/207.jpg", alt: "Art 207" },
        { type: "image", src: "Image/208.jpg", alt: "Art 208" },
        { type: "image", src: "Image/209.jpg", alt: "Art 209" },
        { type: "image", src: "Image/210.jpg", alt: "Art 210" },
        { type: "image", src: "Image/211.jpg", alt: "Art 211" },
        { type: "image", src: "Image/212.jpg", alt: "Art 212" },
        { type: "image", src: "Image/213.jpg", alt: "Art 213" },
        { type: "image", src: "Image/214.jpg", alt: "Art 214" },
        { type: "image", src: "Image/215.jpg", alt: "Art 215" },
        { type: "image", src: "Image/216.jpg", alt: "Art 216" },
        { type: "image", src: "Image/217.jpg", alt: "Art 217" },
        { type: "image", src: "Image/218.jpg", alt: "Art 218" },
        { type: "image", src: "Image/219.jpg", alt: "Art 219" },
        { type: "image", src: "Image/220.jpg", alt: "Art 220" },
        { type: "image", src: "Image/221.jpg", alt: "Art 221" },
        { type: "image", src: "Image/222.jpg", alt: "Art 222" },
        { type: "image", src: "Image/223.jpg", alt: "Art 223" },
        { type: "image", src: "Image/224.jpg", alt: "Art 224" },
        { type: "image", src: "Image/225.jpg", alt: "Art 225" },
        { type: "image", src: "Image/226.jpg", alt: "Art 226" },
        { type: "image", src: "Image/227.jpg", alt: "Art 227" },
        { type: "image", src: "Image/228.jpg", alt: "Art 228" },
        { type: "image", src: "Image/229.jpg", alt: "Art 229" },
        { type: "image", src: "Image/230.jpg", alt: "Art 230" },
        { type: "image", src: "Image/231.jpg", alt: "Art 231" },
        { type: "image", src: "Image/232.jpg", alt: "Art 232" },
        { type: "image", src: "Image/233.jpg", alt: "Art 233" },
        { type: "image", src: "Image/234.jpg", alt: "Art 234" },
        { type: "image", src: "Image/235.jpg", alt: "Art 235" },
        { type: "image", src: "Image/236.jpg", alt: "Art 236" },
        { type: "image", src: "Image/237.jpg", alt: "Art 237" },
        { type: "image", src: "Image/238.jpg", alt: "Art 238" },
        { type: "image", src: "Image/239.jpg", alt: "Art 239" },
        { type: "image", src: "Image/240.jpg", alt: "Art 240" },
        { type: "image", src: "Image/241.jpg", alt: "Art 241" },
        { type: "image", src: "Image/242.jpg", alt: "Art 242" },
        { type: "image", src: "Image/243.jpg", alt: "Art 243" },
        { type: "image", src: "Image/244.jpg", alt: "Art 244" },
        { type: "image", src: "Image/245.jpg", alt: "Art 245" },
        { type: "image", src: "Image/246.jpg", alt: "Art 246" },
        { type: "image", src: "Image/247.jpg", alt: "Art 247" },
        { type: "image", src: "Image/248.jpg", alt: "Art 248" },
        { type: "image", src: "Image/249.jpg", alt: "Art 249" },
        { type: "image", src: "Image/250.jpg", alt: "Art 250" },
        { type: "image", src: "Image/251.jpg", alt: "Art 251" },
        { type: "image", src: "Image/252.jpg", alt: "Art 252" },
        { type: "image", src: "Image/253.jpg", alt: "Art 253" },
        { type: "image", src: "Image/254.jpg", alt: "Art 254" },
        { type: "image", src: "Image/255.jpg", alt: "Art 255" },
        { type: "image", src: "Image/256.jpg", alt: "Art 256" },
        {type: "image", src: "Image/257.jpg", alt: "Art 257" },
        {type: "image", src: "Image/258.jpg", alt: "Art 258" },
        {type: "image", src: "Image/259.jpg", alt: "Art 259" },
        {type: "image", src: "Image/260.jpg", alt: "Art 260" },
        {type: "image", src: "Image/261.jpg", alt: "Art 261" },
        {type: "image", src: "Image/262.jpg", alt: "Art 262" },
        {type: "image", src: "Image/263.jpg", alt: "Art 263" },
        {type: "image", src: "Image/264.jpg", alt: "Art 264" },
        {type: "image", src: "Image/265.jpg", alt: "Art 265" },
        {type: "image", src: "Image/266.jpg", alt: "Art 266" },
        {type: "image", src: "Image/267.jpg", alt: "Art 267" },
        {type: "image", src: "Image/268.jpg", alt: "Art 268" },
        {type: "image", src: "Image/269.jpg", alt: "Art 269" },
        {type: "image", src: "Image/270.jpg", alt: "Art 270" },
        {type: "image", src: "Image/271.jpg", alt: "Art 271" },
        { type: "video", src: "Video/7.mp4", alt: "Video 7" },
        { type: "video", src: "Video/8.mp4", alt: "Video 8" },
        { type: "video", src: "Video/9.mp4", alt: "Video 9" },
        { type: "video", src: "Video/10.mp4", alt: "Video 10" },
        { type: "video", src: "Video/11.mp4", alt: "Video 11" },
        { type: "video", src: "Video/12.mp4", alt: "Video 12" },
        { type: "video", src: "Video/13.mp4", alt: "Video 13" },
        { type: "video", src: "Video/14.mp4", alt: "Video 14" },
        { type: "video", src: "Video/15.mp4", alt: "Video 15" },
        { type: "video", src: "Video/16.mp4", alt: "Video 16" },
        { type: "video", src: "Video/17.mp4", alt: "Video 17" },
        { type: "video", src: "Video/18.mp4", alt: "Video 18" },
        { type: "video", src: "Video/19.mp4", alt: "Video 19" },
        { type: "video", src: "Video/20.mp4", alt: "Video 20" },
        { type: "video", src: "Video/21.mp4", alt: "Video 21" },
        { type: "video", src: "Video/22.mp4", alt: "Video 22" },
        { type: "video", src: "Video/23.mp4", alt: "Video 23" },
        { type: "video", src: "Video/24.mp4", alt: "Video 24" },
        { type: "video", src: "Video/25.mp4", alt: "Video 25" },
        { type: "video", src: "Video/26.mp4", alt: "Video 26" },
        { type: "video", src: "Video/27.mp4", alt: "Video 27" },
        { type: "video", src: "Video/28.mp4", alt: "Video 28" },
        { type: "video", src: "Video/29.mp4", alt: "Video 29" },
        { type: "video", src: "Video/30.mp4", alt: "Video 30" },
        { type: "video", src: "Video/31.mp4", alt: "Video 31" },
        { type: "video", src: "Video/32.mp4", alt: "Video 32" },
        { type: "video", src: "Video/33.mp4", alt: "Video 33" },
        { type: "video", src: "Video/34.mp4", alt: "Video 34" },
        { type: "video", src: "Video/35.mp4", alt: "Video 35" },
        { type: "video", src: "Video/36.mp4", alt: "Video 36" },
        { type: "video", src: "Video/37.mp4", alt: "Video 37" },
        { type: "video", src: "Video/38.mp4", alt: "Video 38" },
        { type: "video", src: "Video/39.mp4", alt: "Video 39" },
        { type: "video", src: "Video/40.mp4", alt: "Video 40" },
        { type: "video", src: "Video/41.mp4", alt: "Video 41" },
        { type: "video", src: "Video/42.mp4", alt: "Video 42" },
        { type: "video", src: "Video/43.mp4", alt: "Video 43" },
        { type: "image", src: "Image/272.jpg", alt: "Art 272" },
        { type: "image", src: "Image/273.jpg", alt: "Art 273" },
        { type: "image", src: "Image/274.jpg", alt: "Art 274" },
        { type: "image", src: "Image/275.jpg", alt: "Art 275" },
        { type: "image", src: "Image/276.jpg", alt: "Art 276" },
        { type: "image", src: "Image/277.jpg", alt: "Art 277" },
        { type: "image", src: "Image/278.jpg", alt: "Art 278" },
        { type: "image", src: "Image/279.jpg", alt: "Art 279" },
        { type: "image", src: "Image/280.jpg", alt: "Art 280" },
        { type: "image", src: "Image/281.jpg", alt: "Art 281" },
        { type: "image", src: "Image/282.jpg", alt: "Art 282" },
        { type: "image", src: "Image/283.jpg", alt: "Art 283" },
        { type: "image", src: "Image/284.jpg", alt: "Art 284" },
        { type: "image", src: "Image/285.jpg", alt: "Art 285" },
        { type: "image", src: "Image/286.jpg", alt: "Art 286" },
        { type: "image", src: "Image/287.jpg", alt: "Art 287" },
        { type: "image", src: "Image/288.jpg", alt: "Art 288" },
        { type: "image", src: "Image/289.jpg", alt: "Art 289" },
        { type: "image", src: "Image/290.jpg", alt: "Art 290" },
        { type: "image", src: "Image/291.jpg", alt: "Art 291" },
        { type: "image", src: "Image/292.jpg", alt: "Art 292" },
        { type: "image", src: "Image/293.jpg", alt: "Art 293" },
        { type: "image", src: "Image/294.jpg", alt: "Art 294" },
        { type: "image", src: "Image/295.jpg", alt: "Art 295" },
        { type: "image", src: "Image/296.jpg", alt: "Art 296" },
        { type: "image", src: "Image/297.jpg", alt: "Art 297" },
        { type: "image", src: "Image/298.jpg", alt: "Art 298" },
        { type: "image", src: "Image/299.jpg", alt: "Art 299" },
        { type: "image", src: "Image/300.jpg", alt: "Art 300" },
        { type: "image", src: "Image/301.jpg", alt: "Art 301" },
        { type: "image", src: "Image/302.jpg", alt: "Art 302" },
        { type: "image", src: "Image/303.jpg", alt: "Art 303" },
        { type: "image", src: "Image/304.jpg", alt: "Art 304" },
        { type: "image", src: "Image/305.jpg", alt: "Art 305" },
        { type: "image", src: "Image/306.jpg", alt: "Art 306" },
        { type: "image", src: "Image/307.jpg", alt: "Art 307" },
        { type: "image", src: "Image/308.jpg", alt: "Art 308" },
        { type: "image", src: "Image/309.jpg", alt: "Art 309" },
        { type: "image", src: "Image/310.jpg", alt: "Art 310" },
        { type: "image", src: "Image/311.jpg", alt: "Art 311" },
        { type: "image", src: "Image/312.jpg", alt: "Art 312" },
        { type: "image", src: "Image/313.jpg", alt: "Art 313" },
        { type: "image", src: "Image/314.jpg", alt: "Art 314" },
        { type: "image", src: "Image/315.jpg", alt: "Art 315" },
        { type: "image", src: "Image/316.jpg", alt: "Art 316" },
        { type: "image", src: "Image/317.jpg", alt: "Art 317" },
        { type: "image", src: "Image/318.jpg", alt: "Art 318" },
        { type: "image", src: "Image/319.jpg", alt: "Art 319" },
        { type: "image", src: "Image/320.jpg", alt: "Art 320" },
        { type: "image", src: "Image/321.jpg", alt: "Art 321" },
        { type: "image", src: "Image/322.jpg", alt: "Art 322" },
        { type: "image", src: "Image/323.jpg", alt: "Art 323" },
        { type: "image", src: "Image/324.jpg", alt: "Art 324" },
        { type: "image", src: "Image/325.jpg", alt: "Art 325" },
        { type: "image", src: "Image/326.jpg", alt: "Art 326" },
        { type: "image", src: "Image/327.jpg", alt: "Art 327" },
        { type: "image", src: "Image/328.jpg", alt: "Art 328" },
        { type: "image", src: "Image/329.jpg", alt: "Art 329" },
        { type: "image", src: "Image/330.jpg", alt: "Art 330" },
        { type: "image", src: "Image/331.jpg", alt: "Art 331" },
        { type: "image", src: "Image/332.jpg", alt: "Art 332" },
        { type: "image", src: "Image/333.jpg", alt: "Art 333" },
        { type: "image", src: "Image/334.jpg", alt: "Art 334" },
        { type: "image", src: "Image/335.jpg", alt: "Art 335" },
        { type: "image", src: "Image/336.jpg", alt: "Art 336" },
        { type: "image", src: "Image/337.jpg", alt: "Art 337" },
        { type: "image", src: "Image/338.jpg", alt: "Art 338" },
        { type: "image", src: "Image/339.jpg", alt: "Art 339" },
        { type: "image", src: "Image/340.jpg", alt: "Art 340" },
        { type: "image", src: "Image/341.jpg", alt: "Art 341" },
        { type: "image", src: "Image/342.jpg", alt: "Art 342" },
        { type: "image", src: "Image/343.jpg", alt: "Art 343" },
        { type: "image", src: "Image/344.jpg", alt: "Art 344" },
        { type: "image", src: "Image/345.jpg", alt: "Art 345" },
        { type: "image", src: "Image/346.jpg", alt: "Art 346" },
        { type: "image", src: "Image/347.jpg", alt: "Art 347" },
        { type: "image", src: "Image/348.jpg", alt: "Art 348" },
        { type: "image", src: "Image/349.jpg", alt: "Art 349" },
        { type: "image", src: "Image/350.jpg", alt: "Art 350" },
        {type: "image", src: "Image/351.jpg", alt: "Art 351" },
        {type: "image", src: "Image/352.jpg", alt: "Art 352" },
        {type: "image", src: "Image/353.jpg", alt: "Art 353" },
        {type: "image", src: "Image/354.jpg", alt: "Art 354" },
        {type: "image", src: "Image/355.jpg", alt: "Art 355" },
        {type: "image", src: "Image/356.jpg", alt: "Art 356" },
        {type: "image", src: "Image/357.jpg", alt: "Art 357" },
        {type: "image", src: "Image/358.jpg", alt: "Art 358" },
        {type: "image", src: "Image/359.jpg", alt: "Art 359" },
        {type: "image", src: "Image/360.jpg", alt: "Art 360" },
         {type: "image", src: "Image/361.jpg", alt: "Art 361" },
        {type: "image", src: "Image/362.jpg", alt: "Art 362" },
        {type: "image", src: "Image/363.jpg", alt: "Art 363" },
        {type: "image", src: "Image/364.jpg", alt: "Art 364" },
        {type: "image", src: "Image/365.jpg", alt: "Art 365" },
        {type: "image", src: "Image/366.jpg", alt: "Art 366" },
        {type: "image", src: "Image/367.jpg", alt: "Art 367" },
        {type: "image", src: "Image/368.jpg", alt: "Art 368" },
        {type: "image", src: "Image/369.jpg", alt: "Art 369" },
        {type: "image", src: "Image/370.jpg", alt: "Art 370" },
        {type: "image", src: "Image/371.jpg", alt: "Art 371" },
        {type: "image", src: "Image/372.jpg", alt: "Art 372" },
        {type: "image", src: "Image/373.jpg", alt: "Art 373" },
        {type: "image", src: "Image/374.jpg", alt: "Art 374" },
        {type: "image", src: "Image/375.jpg", alt: "Art 375" },
        {type: "image", src: "Image/376.jpg", alt: "Art 376" },
        {type: "image", src: "Image/377.jpg", alt: "Art 377" },
        {type: "image", src: "Image/378.jpg", alt: "Art 378" },
        {type: "image", src: "Image/379.jpg", alt: "Art 379" },
        {type: "image", src: "Image/380.jpg", alt: "Art 380" },
        {type: "image", src: "Image/381.jpg", alt: "Art 381" },
        {type: "image", src: "Image/382.jpg", alt: "Art 382" },
        {type: "image", src: "Image/383.jpg", alt: "Art 383" },
        {type: "image", src: "Image/384.jpg", alt: "Art 384" },
        {type: "image", src: "Image/385.jpg", alt: "Art 385" },
        {type: "image", src: "Image/386.jpg", alt: "Art 386" },
        {type: "image", src: "Image/387.jpg", alt: "Art 387" },
        {type: "image", src: "Image/388.jpg", alt: "Art 388" },
        {type: "image", src: "Image/389.jpg", alt: "Art 389" },
        {type: "image", src: "Image/390.jpg", alt: "Art 390" },
        {type: "image", src: "Image/391.jpg", alt: "Art 391" },
        {type: "image", src: "Image/392.jpg", alt: "Art 392" },
        {type: "image", src: "Image/393.jpg", alt: "Art 393" },
        {type: "image", src: "Image/394.jpg", alt: "Art 394" },
        {type: "image", src: "Image/395.jpg", alt: "Art 395" },
        {type: "image", src: "Image/396.jpg", alt: "Art 396" },
        {type: "image", src: "Image/397.jpg", alt: "Art 397" },
        {type: "image", src: "Image/398.jpg", alt: "Art 398" },
        {type: "image", src: "Image/399.jpg", alt: "Art 399" },
        {type: "image", src: "Image/400.jpg", alt: "Art 400" },
        {type: "image", src: "Image/401.jpg", alt: "Art 401" },
        {type: "image", src: "Image/402.jpg", alt: "Art 402" },
        {type: "image", src: "Image/403.jpg", alt: "Art 403" },
        {type: "image", src: "Image/404.jpg", alt: "Art 404" },
        {type: "image", src: "Image/405.jpg", alt: "Art 405" },
        {type: "image", src: "Image/406.jpg", alt: "Art 406" },
        {type: "image", src: "Image/407.jpg", alt: "Art 407" },
        {type: "image", src: "Image/408.jpg", alt: "Art 408" },
        {type: "image", src: "Image/409.jpg", alt: "Art 409" },
        {type: "image", src: "Image/410.jpg", alt: "Art 410" },
        {tupe: "image", src: "Image/411.jpg", alt: "Art 411" },
        {type: "image", src: "Image/412.jpg", alt: "Art 412" },
        {type: "image", src: "Image/413.jpg", alt: "Art 413" },
        {type: "image", src: "Image/414.jpg", alt: "Art 414" },
        {type: "image", src: "Image/415.jpg", alt: "Art 415" },
        {type: "image", src: "Image/416.jpg", alt: "Art 416" },
        {type: "image", src: "Image/417.jpg", alt: "Art 417" },
        {type: "image", src: "Image/418.jpg", alt: "Art 418" },
        {type: "image", src: "Image/419.jpg", alt: "Art 419" },
        {type: "image", src: "Image/420.jpg", alt: "Art 420" },
        {type: "image", src: "Image/421.jpg", alt: "Art 421" },
        {type: "image", src: "Image/422.jpg", alt: "Art 422" },
        {type: "image", src: "Image/423.jpg", alt: "Art 423" },
        {type: "image", src: "Image/424.jpg", alt: "Art 424" },
        {type: "image", src: "Image/425.jpg", alt: "Art 425" },
        {type: "image", src: "Image/426.jpg", alt: "Art 426" },
        {type: "image", src: "Image/427.jpg", alt: "Art 427" },
        {type: "image", src: "Image/428.jpg", alt: "Art 428" },
        {type: "image", src: "Image/429.jpg", alt: "Art 429" },
        {type: "image", src: "Image/430.jpg", alt: "Art 430" },
        {type: "image", src: "Image/431.jpg", alt: "Art 431" },
        {type: "image", src: "Image/432.jpg", alt: "Art 432" },
        {type: "image", src: "Image/433.jpg", alt: "Art 433" },
        {type: "image", src: "Image/434.jpg", alt: "Art 434" },
        {type: "image", src: "Image/435.jpg", alt: "Art 435" },
        {type: "image", src: "Image/436.jpg", alt: "Art 436" },
        {type: "image", src: "Image/437.jpg", alt: "Art 437" },
        {type: "image", src: "Image/438.jpg", alt: "Art 438" },
        {type: "image", src: "Image/439.jpg", alt: "Art 439" },
        {type: "image", src: "Image/440.jpg", alt: "Art 440" },
        {type: "image", src: "Image/441.jpg", alt: "Art 441" },
        {type: "image", src: "Image/442.jpg", alt: "Art 442" },
        {type: "image", src: "Image/443.jpg", alt: "Art 443" },
        {type: "image", src: "Image/444.jpg", alt: "Art 444" },
        {type: "image", src: "Image/445.jpg", alt: "Art 445" },
        {type: "image", src: "Image/446.jpg", alt: "Art 446" },
        {type: "image", src: "Image/447.jpg", alt: "Art 447" },
        {type: "image", src: "Image/448.jpg", alt: "Art 448" },
        {type: "image", src: "Image/449.jpg", alt: "Art 449" },
        {type: "image", src: "Image/450.jpg", alt: "Art 450" },
        {type: "image", src: "Image/451.jpg", alt: "Art 451" },
        {type: "image", src: "Image/452.jpg", alt: "Art 452" },
        {type: "image", src: "Image/453.jpg", alt: "Art 453" },
        {type: "image", src: "Image/454.jpg", alt: "Art 454" },
        {type: "image", src: "Image/455.jpg", alt: "Art 455" },
        {type: "image", src: "Image/456.jpg", alt: "Art 456" },
        {type: "image", src: "Image/457.jpg", alt: "Art 457" },
        {type: "image", src: "Image/458.jpg", alt: "Art 458" },
        {type: "image", src: "Image/459.jpg", alt: "Art 459" },
        {type: "image", src: "Image/460.jpg", alt: "Art 460" },
        {type: "image", src: "Image/461.jpg", alt: "Art 461" },
        {type: "image", src: "Image/462.jpg", alt: "Art 462" },
        {type: "image", src: "Image/463.jpg", alt: "Art 463" },
        {type: "image", src: "Image/464.jpg", alt: "Art 464" },
        {type: "image", src: "Image/465.jpg", alt: "Art 465" },
        {type: "image", src: "Image/466.jpg", alt: "Art 466" },
        {type: "image", src: "Image/467.jpg", alt: "Art 467" },
        {type: "image", src: "Image/468.jpg", alt: "Art 468" },
        {type: "image", src: "Image/469.jpg", alt: "Art 469" },
        {type: "image", src: "Image/470.jpg", alt: "Art 470" },
        {type: "image", src: "Image/471.jpg", alt: "Art 471" },
        {type: "image", src: "Image/472.jpg", alt: "Art 472" },
        {type: "image", src: "Image/473.jpg", alt: "Art 473" },
        {type: "image", src: "Image/474.jpg", alt: "Art 474" },
        {type: "image", src: "Image/475.jpg", alt: "Art 475" },
        {type: "image", src: "Image/476.jpg", alt: "Art 476" },
        {type: "image", src: "Image/477.jpg", alt: "Art 477" },
        {type: "image", src: "Image/478.jpg", alt: "Art 478" },
        {type: "image", src: "Image/479.jpg", alt: "Art 479" },
        {type: "image", src: "Image/480.jpg", alt: "Art 480" },
        {type: "image", src: "Image/481.jpg", alt: "Art 481" },
        {type: "image", src: "Image/482.jpg", alt: "Art 482" },
        {type: "image", src: "Image/483.jpg", alt: "Art 483" },
        {type: "image", src: "Image/484.jpg", alt: "Art 484" },
        {type: "image", src: "Image/485.jpg", alt: "Art 485" },
        {type: "image", src: "Image/486.jpg", alt: "Art 486" },
        {type: "image", src: "Image/487.jpg", alt: "Art 487" },
        {type: "image", src: "Image/488.jpg", alt: "Art 488" },
        {type: "image", src: "Image/489.jpg", alt: "Art 489" },
        {type: "image", src: "Image/490.jpg", alt: "Art 490" },
        {type: "image", src: "Image/491.jpg", alt: "Art 491" },
        {type: "image", src: "Image/492.jpg", alt: "Art 492" },
        {type: "image", src: "Image/493.jpg", alt: "Art 493" },
        {type: "image", src: "Image/494.jpg", alt: "Art 494" },
        {type: "image", src: "Image/495.jpg", alt: "Art 495" },
        {type: "image", src: "Image/496.jpg", alt: "Art 496" },
        {type: "image", src: "Image/497.jpg", alt: "Art 497" },
        {type: "image", src: "Image/498.jpg", alt: "Art 498" },
        {type: "image", src: "Image/499.jpg", alt: "Art 499" },
        {type: "image", src: "Image/500.jpg", alt: "Art 500" },
        {type: "image", src: "Image/501.jpg", alt: "Art 501" },
        {type: "image", src: "Image/502.jpg", alt: "Art 502" },
        {type: "image", src: "Image/503.jpg", alt: "Art 503" },
        {type: "image", src: "Image/504.jpg", alt: "Art 504" },
        {type: "image", src: "Image/505.jpg", alt: "Art 505" },
        {type: "image", src: "Image/506.jpg", alt: "Art 506" },
        {type: "image", src: "Image/507.jpg", alt: "Art 507" },
        {type: "image", src: "Image/508.jpg", alt: "Art 508" },
        {type: "image", src: "Image/509.jpg", alt: "Art 509" },
        {type: "image", src: "Image/510.jpg", alt: "Art 510" },
        {type: "image", src: "Image/511.jpg", alt: "Art 511" },
        {type: "image", src: "Image/512.jpg", alt: "Art 512" },
        {type: "image", src: "Image/513.jpg", alt: "Art 513" },
        {type: "image", src: "Image/514.jpg", alt: "Art 514" },
        {type: "image", src: "Image/515.jpg", alt: "Art 515" },
        {type: "image", src: "Image/516.jpg", alt: "Art 516" },
        {type: "image", src: "Image/517.jpg", alt: "Art 517" },
        {type: "image", src: "Image/518.jpg", alt: "Art 518" },
        {type: "image", src: "Image/519.jpg", alt: "Art 519" },
        {type: "image", src: "Image/520.jpg", alt: "Art 520" },
        {type: "image", src: "Image/521.jpg", alt: "Art 521" },
        {type: "image", src: "Image/522.jpg", alt: "Art 522" },
        {type: "image", src: "Image/523.jpg", alt: "Art 523" },
        {type: "image", src: "Image/524.jpg", alt: "Art 524" },
        {type: "image", src: "Image/525.jpg", alt: "Art 525" },
        {type: "image", src: "Image/526.jpg", alt: "Art 526" },
        {type: "image", src: "Image/527.jpg", alt: "Art 527" },
        {type: "image", src: "Image/528.jpg", alt: "Art 528" },
        {type: "image", src: "Image/529.jpg", alt: "Art 529" },
        {type: "image", src: "Image/530.jpg", alt: "Art 530" },
        {type: "image", src: "Image/IMG_4844.jpg", alt: "Art IMG_4844" },
        {type: "image", src: "Image/IMG_4847.jpg", alt: "Art IMG_4847" },
        {type: "image", src: "Image/IMG_4848.jpg", alt: "Art IMG_4848" },
        {type: "image", src: "Image/IMG_4849.jpg", alt: "Art IMG_4849" },
        {type: "image", src: "Image/IMG_4850.jpg", alt: "Art IMG_4850" },
        {type: "image", src: "Image/IMG_4851.jpg", alt: "Art IMG_4851" },
        {type: "image", src: "Image/IMG_4852.jpg", alt: "Art IMG_4852" },
        {type: "image", src: "Image/IMG_4853.jpg", alt: "Art IMG_4853" },
        {type: "image", src: "Image/IMG_4854.jpg", alt: "Art IMG_4854" },
        {type: "image", src: "Image/IMG_4855.jpg", alt: "Art IMG_4855" },
        {type: "image", src: "Image/IMG_4856.jpg", alt: "Art IMG_4856" },
        {type: "image", src: "Image/IMG_4857.jpg", alt: "Art IMG_4857" },
        {type: "image", src: "Image/IMG_4858.jpg", alt: "Art IMG_4858" },
        {type: "image", src: "Image/IMG_4859.jpg", alt: "Art IMG_4859" },
        {type: "image", src: "Image/IMG_4860.jpg", alt: "Art IMG_4860" },
        {type: "image", src: "Image/IMG_4861.jpg", alt: "Art IMG_4861" },
        {type: "image", src: "Image/IMG_4862.jpg", alt: "Art IMG_4862" },
        {type: "image", src: "Image/IMG_4863.jpg", alt: "Art IMG_4863" },
        {type: "image", src: "Image/IMG_4864.jpg", alt: "Art IMG_4864" },
        {type: "image", src: "Image/IMG_4865.jpg", alt: "Art IMG_4865" },
        {type: "image", src: "Image/IMG_4866.jpg", alt: "Art IMG_4866" },
        {type: "image", src: "Image/IMG_4867.jpg", alt: "Art IMG_4867" },
        {type: "image", src: "Image/IMG_4868.jpg", alt: "Art IMG_4868" },
        {type: "image", src: "Image/IMG_4869.jpg", alt: "Art IMG_4869" },
        {type: "image", src: "Image/IMG_4870.jpg", alt: "Art IMG_4870" },
        {type: "image", src: "Image/IMG_4871.jpg", alt: "Art IMG_4871" },
        {type: "image", src: "Image/IMG_4872.jpg", alt: "Art IMG_4872" },
        {type: "image", src: "Image/IMG_4873.jpg", alt: "Art IMG_4873" },
        {type: "image", src: "Image/IMG_4874.jpg", alt: "Art IMG_4874" },
        {type: "image", src: "Image/IMG_4875.jpg", alt: "Art IMG_4875" },
        {type: "image", src: "Image/IMG_4876.jpg", alt: "Art IMG_4876" },
        {type: "image", src: "Image/IMG_4877.jpg", alt: "Art IMG_4877" },
        {type: "image", src: "Image/IMG_4878.jpg", alt: "Art IMG_4878" },
        {type: "image", src: "Image/IMG_4879.jpg", alt: "Art IMG_4879" },
        {type: "image", src: "Image/IMG_4880.jpg", alt: "Art IMG_4880" },
        {type: "image", src: "Image/IMG_4881.jpg", alt: "Art IMG_4881" },
        {type: "image", src: "Image/IMG_4882.jpg", alt: "Art IMG_4882" },
        {type: "image", src: "Image/IMG_4883.jpg", alt: "Art IMG_4883" },
        {type: "image", src: "Image/IMG_4884.jpg", alt: "Art IMG_4884" },
        {type: "image", src: "Image/IMG_4885.jpg", alt: "Art IMG_4885" },
        {type: "image", src: "Image/IMG_4886.jpg", alt: "Art IMG_4886" },
        {type: "image", src: "Image/IMG_4887.jpg", alt: "Art IMG_4887" },
        {type: "image", src: "Image/IMG_4888.jpg", alt: "Art IMG_4888" },
        {type: "image", src: "Image/IMG_4889.jpg", alt: "Art IMG_4889" },
        {type: "image", src: "Image/IMG_4890.jpg", alt: "Art IMG_4890" },
        {type: "image", src: "Image/IMG_4891.jpg", alt: "Art IMG_4891" },
        {type: "image", src: "Image/IMG_4892.jpg", alt: "Art IMG_4892" },
        {type: "image", src: "Image/IMG_4893.jpg", alt: "Art IMG_4893" },
        {type: "image", src: "Image/IMG_4894.jpg", alt: "Art IMG_4894" },
        {type: "image", src: "Image/IMG_4895.jpg", alt: "Art IMG_4895" },
        {type: "image", src: "Image/IMG_4896.jpg", alt: "Art IMG_4896" },
        {type: "image", src: "Image/IMG_4897.jpg", alt: "Art IMG_4897" },
        {type: "image", src: "Image/IMG_4898.jpg", alt: "Art IMG_4898" },
        {type: "image", src: "Image/IMG_4899.jpg", alt: "Art IMG_4899" },
        {type: "image", src: "Image/IMG_4900.jpg", alt: "Art IMG_4900" },
        {type: "image", src: "Image/IMG_4901.jpg", alt: "Art IMG_4901" },
        {type: "image", src: "Image/IMG_4902.jpg", alt: "Art IMG_4902" },
        {type: "image", src: "Image/IMG_4903.jpg", alt: "Art IMG_4903" },
        {type: "image", src: "Image/IMG_4904.jpg", alt: "Art IMG_4904" },
        {type: "image", src: "Image/IMG_4905.jpg", alt: "Art IMG_4905" },
        {type: "image", src: "Image/IMG_4906.jpg", alt: "Art IMG_4906" },
        {type: "image", src: "Image/IMG_4907.jpg", alt: "Art IMG_4907" },
        {type: "image", src: "Image/IMG_4908.jpg", alt: "Art IMG_4908" },
        {type: "image", src: "Image/IMG_4909.jpg", alt: "Art IMG_4909" },
        {type: "image", src: "Image/IMG_4911.jpg", alt: "Art IMG_4911" },
        {type: "image", src: "Image/IMG_4912.jpg", alt: "Art IMG_4912" },
        {type: "image", src: "Image/IMG_4913.jpg", alt: "Art IMG_4913" },
        {type: "image", src: "Image/IMG_4914.jpg", alt: "Art IMG_4914" },
        {type: "image", src: "Image/IMG_4915.jpg", alt: "Art IMG_4915" },
        {type: "image", src: "Image/IMG_4916.jpg", alt: "Art IMG_4916" },
        {type: "image", src: "Image/IMG_4917.jpg", alt: "Art IMG_4917" },
        {type: "image", src: "Image/IMG_4918.jpg", alt: "Art IMG_4918" },
        {type: "image", src: "Image/IMG_4919.jpg", alt: "Art IMG_4919" },
        {type: "image", src: "Image/IMG_4920.jpg", alt: "Art IMG_4920" },
        {type: "image", src: "Image/IMG_4921.jpg", alt: "Art IMG_4921" },
        {type: "image", src: "Image/IMG_4933.jpg", alt: "Art IMG_4933" },
        {type: "image", src: "Image/IMG_4934.jpg", alt: "Art IMG_4934" },
        {type: "image", src: "Image/IMG_4935.jpg", alt: "Art IMG_4935" },
        {type: "image", src: "Image/IMG_4936.jpg", alt: "Art IMG_4936" },
        {type: "image", src: "Image/IMG_4937.jpg", alt: "Art IMG_4937" },
        {type: "image", src: "Image/IMG_4938.jpg", alt: "Art IMG_4938" },
        {type: "image", src: "Image/IMG_4961.jpg", alt: "Art IMG_4961" },
        {type: "image", src: "Image/IMG_4962.jpg", alt: "Art IMG_4962" },
        {type: "image", src: "Image/IMG_4963.jpg", alt: "Art IMG_4963" },
        {type: "image", src: "Image/IMG_4964.jpg", alt: "Art IMG_4964" },
        {type: "image", src: "Image/IMG_4965.jpg", alt: "Art IMG_4965" },
        {type: "image", src: "Image/IMG_4966.jpg", alt: "Art IMG_4966" },
        {type: "image", src: "Image/IMG_4967.jpg", alt: "Art IMG_4967" },
        {type: "image", src: "Image/IMG_4968.jpg", alt: "Art IMG_4968" },
        {type: "image", src: "Image/IMG_4969.jpg", alt: "Art IMG_4969" },
        {type: "image", src: "Image/IMG_4970.jpg", alt: "Art IMG_4970" },
        {type: "image", src: "Image/IMG_4971.jpg", alt: "Art IMG_4971" },
        {type: "image", src: "Image/IMG_4972.jpg", alt: "Art IMG_4972" },
        {type: "image", src: "Image/IMG_4973.jpg", alt: "Art IMG_4973" },
        {type: "image", src: "Image/IMG_4974.jpg", alt: "Art IMG_4974" },
        {type: "image", src: "Image/IMG_4975.jpg", alt: "Art IMG_4975" },
        {type: "image", src: "Image/IMG_4976.jpg", alt: "Art IMG_4976" },
        {type: "image", src: "Image/IMG_4977.jpg", alt: "Art IMG_4977" },
        {type: "image", src: "Image/IMG_4978.jpg", alt: "Art IMG_4978" },
        {type: "image", src: "Image/IMG_4979.jpg", alt: "Art IMG_4979" },
        {type: "image", src: "Image/IMG_4980.jpg", alt: "Art IMG_4980" },
        {type: "image", src: "Image/IMG_4981.jpg", alt: "Art IMG_4981" },
        {type: "image", src: "Image/IMG_4982.jpg", alt: "Art IMG_4982" },
        {type: "image", src: "Image/IMG_4983.jpg", alt: "Art IMG_4983" },
        {type: "image", src: "Image/IMG_4984.jpg", alt: "Art IMG_4984" },
        {type: "image", src: "Image/IMG_4985.jpg", alt: "Art IMG_4985" },
        {type: "image", src: "Image/IMG_4986.jpg", alt: "Art IMG_4986" },
        {type: "image", src: "Image/IMG_4987.jpg", alt: "Art IMG_4987" },
        {type: "image", src: "Image/IMG_4988.jpg", alt: "Art IMG_4988" },
        {type: "image", src: "Image/IMG_4989.jpg", alt: "Art IMG_4989" },
        {type: "image", src: "Image/IMG_4990.jpg", alt: "Art IMG_4990" },
        {type: "image", src: "Image/IMG_4991.jpg", alt: "Art IMG_4991" },
        {type: "image", src: "Image/IMG_4992.jpg", alt: "Art IMG_4992" },
        {type: "image", src: "Image/IMG_4993.jpg", alt: "Art IMG_4993" },
        {type: "image", src: "Image/IMG_4994.jpg", alt: "Art IMG_4994" },
        {type: "image", src: "Image/IMG_4995.jpg", alt: "Art IMG_4995" },
        {type: "image", src: "Image/IMG_4996.jpg", alt: "Art IMG_4996" },
        {type: "image", src: "Image/IMG_4997.jpg", alt: "Art IMG_4997" },
        {type: "image", src: "Image/IMG_4998.jpg", alt: "Art IMG_4998" },
        {type: "image", src: "Image/IMG_4999.jpg", alt: "Art IMG_4999" },
        {type: "image", src: "Image/IMG_5001.jpg", alt: "Art IMG_5001" },
        {type: "image", src: "Image/IMG_5002.jpg", alt: "Art IMG_5002" },
        {type: "image", src: "Image/IMG_5003.jpg", alt: "Art IMG_5003" },
        {type: "image", src: "Image/IMG_5004.jpg", alt: "Art IMG_5004" },
        {type: "image", src: "Image/IMG_5005.jpg", alt: "Art IMG_5005" },
        {type: "image", src: "Image/IMG_5006.jpg", alt: "Art IMG_5006" },
        {type: "image", src: "Image/IMG_5007.jpg", alt: "Art IMG_5007" },
        {type: "image", src: "Image/IMG_5008.jpg", alt: "Art IMG_5008" },
        {type: "image", src: "Image/IMG_5009.jpg", alt: "Art IMG_5009" },
        {type: "image", src: "Image/IMG_5010.jpg", alt: "Art IMG_5010" },
        {type: "image", src: "Image/IMG_5011.jpg", alt: "Art IMG_5011" },
        {type: "image", src: "Image/IMG_5012.jpg", alt: "Art IMG_5012" },
        {type: "image", src: "Image/IMG_5013.jpg", alt: "Art IMG_5013" },
        {type: "image", src: "Image/IMG_5014.jpg", alt: "Art IMG_5014" },
        {type: "image", src: "Image/IMG_5015.jpg", alt: "Art IMG_5015" },
        {type: "image", src: "Image/IMG_5016.jpg", alt: "Art IMG_5016" },
        {type: "image", src: "Image/IMG_5017.jpg", alt: "Art IMG_5017" },
        {type: "image", src: "Image/IMG_5018.jpg", alt: "Art IMG_5018" },
        {type: "image", src: "Image/IMG_5019.jpg", alt: "Art IMG_5019" },
        {type: "image", src: "Image/IMG_5020.jpg", alt: "Art IMG_5020" },
        {type: "image", src: "Image/IMG_5021.jpg", alt: "Art IMG_5021" },
        {type: "image", src: "Image/IMG_5022.jpg", alt: "Art IMG_5022" },
        {type: "image", src: "Image/IMG_5023.jpg", alt: "Art IMG_5023" },
        {type: "image", src: "Image/IMG_5024.jpg", alt: "Art IMG_5024" },
        {type: "image", src: "Image/IMG_5025.jpg", alt: "Art IMG_5025" },
        {type: "image", src: "Image/IMG_5026.jpg", alt: "Art IMG_5026" },
        {type: "image", src: "Image/IMG_5027.jpg", alt: "Art IMG_5027" },
        {type: "image", src: "Image/IMG_5028.jpg", alt: "Art IMG_5028" },
        {type: "image", src: "Image/IMG_5029.jpg", alt: "Art IMG_5029" },
        {type: "image", src: "Image/IMG_5030.jpg", alt: "Art IMG_5030" },
        {type: "image", src: "Image/IMG_5031.jpg", alt: "Art IMG_5031" },
        {type: "image", src: "Image/IMG_5032.jpg", alt: "Art IMG_5032" },
        {type: "image", src: "Image/IMG_5033.jpg", alt: "Art IMG_5033" },
        {type: "image", src: "Image/IMG_5034.jpg", alt: "Art IMG_5034" },
        {type: "image", src: "Image/IMG_5035.jpg", alt: "Art IMG_5035" },
        {type: "image", src: "Image/IMG_5036.jpg", alt: "Art IMG_5036" },
        {type: "image", src: "Image/IMG_5037.jpg", alt: "Art IMG_5037" },
        {type: "image", src: "Image/IMG_5038.jpg", alt: "Art IMG_5038" },
        {type: "image", src: "Image/IMG_5039.jpg", alt: "Art IMG_5039" },
        {type: "image", src: "Image/IMG_5040.jpg", alt: "Art IMG_5040" },
        {type: "image", src: "Image/IMG_5041.jpg", alt: "Art IMG_5041" },
        {type: "image", src: "Image/IMG_5042.jpg", alt: "Art IMG_5042" },
        {type: "image", src: "Image/IMG_5043.jpg", alt: "Art IMG_5043" },
        {type: "image", src: "Image/IMG_5044.jpg", alt: "Art IMG_5044" },
        {type: "image", src: "Image/IMG_5045.jpg", alt: "Art IMG_5045" },
        {type: "image", src: "Image/IMG_5046.jpg", alt: "Art IMG_5046" },
        {type: "image", src: "Image/IMG_5047.jpg", alt: "Art IMG_5047" },
        {type: "image", src: "Image/IMG_5048.jpg", alt: "Art IMG_5048" },
        {type: "image", src: "Image/IMG_5049.jpg", alt: "Art IMG_5049" },
        {type: "image", src: "Image/IMG_5050.jpg", alt: "Art IMG_5050" },
        {type: "image", src: "Image/IMG_5051.jpg", alt: "Art IMG_5051" },
        {type: "image", src: "Image/IMG_5052.jpg", alt: "Art IMG_5052" },
        {type: "image", src: "Image/IMG_5053.jpg", alt: "Art IMG_5053" },
        {type: "image", src: "Image/IMG_5054.jpg", alt: "Art IMG_5054" },
        {type: "image", src: "Image/IMG_5055.jpg", alt: "Art IMG_5055" },
        {type: "image", src: "Image/IMG_5056.jpg", alt: "Art IMG_5056" },
        {type: "image", src: "Image/IMG_5057.jpg", alt: "Art IMG_5057" },
        {type: "image", src: "Image/IMG_5058.jpg", alt: "Art IMG_5058" },
        {type: "image", src: "Image/IMG_5059.jpg", alt: "Art IMG_5059" },
        {type: "image", src: "Image/IMG_5060.jpg", alt: "Art IMG_5060" },
        {type: "image", src: "Image/IMG_5061.jpg", alt: "Art IMG_5061" },
        {type: "image", src: "Image/IMG_5062.jpg", alt: "Art IMG_5062" },
        {type: "image", src: "Image/IMG_5063.jpg", alt: "Art IMG_5063" },
        {type: "image", src: "Image/IMG_5064.jpg", alt: "Art IMG_5064" },
        {type: "image", src: "Image/IMG_5065.jpg", alt: "Art IMG_5065" },
        {type: "image", src: "Image/IMG_5066.jpg", alt: "Art IMG_5066" },
        {type: "image", src: "Image/IMG_5067.jpg", alt: "Art IMG_5067" },
        {type: "image", src: "Image/IMG_5068.jpg", alt: "Art IMG_5068" },
        {type: "image", src: "Image/IMG_5069.jpg", alt: "Art IMG_5069" },
        {type: "image", src: "Image/IMG_5070.jpg", alt: "Art IMG_5070" },
        {type: "image", src: "Image/IMG_5071.jpg", alt: "Art IMG_5071" },
        {type: "image", src: "Image/IMG_5072.jpg", alt: "Art IMG_5072" },
        {type: "image", src: "Image/IMG_5073.jpg", alt: "Art IMG_5073" },
        {type: "image", src: "Image/IMG_5086.jpg", alt: "Art IMG_5086" },
        {type: "image", src: "Image/IMG_5087.jpg", alt: "Art IMG_5087" },
        {type: "image", src: "Image/IMG_5088.jpg", alt: "Art IMG_5088" },
        {type: "image", src: "Image/IMG_5089.jpg", alt: "Art IMG_5089" },
        {type: "image", src: "Image/IMG_5090.jpg", alt: "Art IMG_5090" },
        {type: "image", src: "Image/IMG_5091.jpg", alt: "Art IMG_5091" },
        {type: "image", src: "Image/IMG_5092.jpg", alt: "Art IMG_5092" },
        {type: "image", src: "Image/IMG_5093.jpg", alt: "Art IMG_5093" },
        {type: "image", src: "Image/IMG_5094.jpg", alt: "Art IMG_5094" },
        {type: "image", src: "Image/IMG_5095.jpg", alt: "Art IMG_5095" },
        {type: "image", src: "Image/IMG_5096.jpg", alt: "Art IMG_5096" },
        {type: "image", src: "Image/IMG_5097.jpg", alt: "Art IMG_5097" },
        {type: "image", src: "Image/IMG_5098.jpg", alt: "Art IMG_5098" },
        {type: "image", src: "Image/IMG_5099.jpg", alt: "Art IMG_5099" },
        {type: "image", src: "Image/IMG_5100.jpg", alt: "Art IMG_5100" },
        {type: "image", src: "Image/IMG_5101.jpg", alt: "Art IMG_5101" },
        {type: "image", src: "Image/IMG_5102.jpg", alt: "Art IMG_5102" },
        {type: "image", src: "Image/IMG_5103.jpg", alt: "Art IMG_5103" },
        {type: "image", src: "Image/IMG_5104.jpg", alt: "Art IMG_5104" },
        {type: "image", src: "Image/IMG_5105.jpg", alt: "Art IMG_5105" },
        {type: "image", src: "Image/IMG_5106.jpg", alt: "Art IMG_5106" },
        {type: "image", src: "Image/IMG_5107.jpg", alt: "Art IMG_5107" },
        {type: "image", src: "Image/IMG_5108.jpg", alt: "Art IMG_5108" },
        {type: "image", src: "Image/IMG_5109.jpg", alt: "Art IMG_5109" },
        {type: "image", src: "Image/IMG_5110.jpg", alt: "Art IMG_5110" },
        {type: "image", src: "Image/IMG_5111.jpg", alt: "Art IMG_5111" },
        {type: "image", src: "Image/IMG_5112.jpg", alt: "Art IMG_5112" },
        {type: "image", src: "Image/IMG_5113.jpg", alt: "Art IMG_5113" },
        {type: "image", src: "Image/IMG_5114.jpg", alt: "Art IMG_5114" },
        {type: "image", src: "Image/IMG_5115.jpg", alt: "Art IMG_5115" },
        {type: "image", src: "Image/IMG_5116.jpg", alt: "Art IMG_5116" },
        {type: "image", src: "Image/IMG_5117.jpg", alt: "Art IMG_5117" },
        {type: "image", src: "Image/IMG_5118.jpg", alt: "Art IMG_5118" },
        {type: "image", src: "Image/IMG_5119.jpg", alt: "Art IMG_5119" },
        {type: "image", src: "Image/IMG_5120.jpg", alt: "Art IMG_5120" },
        {type: "image", src: "Image/IMG_5121.jpg", alt: "Art IMG_5121" },
        {type: "image", src: "Image/IMG_5122.jpg", alt: "Art IMG_5122" },
        {type: "image", src: "Image/IMG_5123.jpg", alt: "Art IMG_5123" },
        {type: "image", src: "Image/IMG_5124.jpg", alt: "Art IMG_5124" },
        {type: "image", src: "Image/IMG_5125.jpg", alt: "Art IMG_5125" },
        {type: "image", src: "Image/IMG_5126.jpg", alt: "Art IMG_5126" },
        {type: "image", src: "Image/IMG_5127.jpg", alt: "Art IMG_5127" },
        {type: "image", src: "Image/IMG_5128.jpg", alt: "Art IMG_5128" },
        {type: "image", src: "Image/IMG_5129.jpg", alt: "Art IMG_5129" },
        {type: "image", src: "Image/IMG_5130.jpg", alt: "Art IMG_5130" },
        {type: "image", src: "Image/IMG_5131.jpg", alt: "Art IMG_5131" },
        {type: "image", src: "Image/IMG_5132.jpg", alt: "Art IMG_5132" },
        {type: "image", src: "Image/IMG_5133.jpg", alt: "Art IMG_5133" },
        {type: "image", src:"Image/IMG_5134.jpg",  alt:  "Art IMG_5134" },
        {type:"image", src:"Image/IMG_5135.jpg",   alt:   "Art IMG_5135" },
        {type:"image", src:"Image/IMG_5136.jpg", alt:   "Art IMG_5136" },
        {type:"image", src:"Image/IMG_5137.jpg", alt:   "Art IMG_5137" },
        {type:"image", src:"Image/IMG_5138.jpg", alt:   "Art IMG_5138" },
        {type:"image", src:"Image/IMG_5139.jpg", alt:   "Art IMG_5139" },
        {type:"image", src:"Image/IMG_5140.jpg", alt:   "Art IMG_5140" },
        {type:"image", src:"Image/IMG_5141.jpg", alt:   "Art IMG_5141" },
        {type:"image", src:"Image/IMG_5142.jpg", alt:   "Art IMG_5142" },
        {type:"image", src:"Image/IMG_5143.jpg", alt:   "Art IMG_5143" },
        {type:"image", src:"Image/IMG_5144.jpg", alt:   "Art IMG_5144" },
        {type:"image", src:"Image/IMG_5145.jpg", alt:   "Art IMG_5145" },
        {type:"image", src:"Image/IMG_5146.jpg", alt:   "Art IMG_5146" },
        {type:"image", src:"Image/IMG_5147.jpg", alt:   "Art IMG_5147" },
        {type:"image", src:"Image/IMG_5148.jpg", alt:   "Art IMG_5148" },
        {type:"image", src:"Image/IMG_5149.jpg", alt:   "Art IMG_5149" },
        {type:"image", src:"Image/IMG_5150.jpg", alt:   "Art IMG_5150" },
        {type:"image", src:"Image/IMG_5151.jpg", alt:   "Art IMG_5151" },
        {type:"image", src:"Image/IMG_5152.jpg", alt:   "Art IMG_5152" },
        {type:"image", src:"Image/IMG_5153.jpg", alt:   "Art IMG_5153" },
        {type:"image", src:"Image/IMG_5154.jpg", alt:   "Art IMG_5154" },
        {type:"image", src:"Image/IMG_5155.jpg", alt:   "Art IMG_5155" },
        {type:"image", src:"Image/IMG_5156.jpg", alt:   "Art IMG_5156" },
        {type:"image", src:"Image/IMG_5157.jpg", alt:   "Art IMG_5157" },
        {type:"image", src:"Image/IMG_5158.jpg", alt:   "Art IMG_5158" },
        {type:"image", src:"Image/IMG_5159.jpg", alt:   "Art IMG_5159" },
        {type:"image", src:"Image/IMG_5160.jpg", alt:   "Art IMG_5160" },
        {type:"image", src:"Image/IMG_5161.jpg", alt:   "Art IMG_5161" },
        {type:"image", src:"Image/IMG_5162.jpg", alt:   "Art IMG_5162" },
        {type:"image", src:"Image/IMG_5163.jpg", alt:   "Art IMG_5163" },
        {type:"image", src:"Image/IMG_5164.jpg", alt:   "Art IMG_5164" },
        {type:"image", src:"Image/IMG_5165.jpg", alt:   "Art IMG_5165" },
        {type:"image", src:"Image/IMG_5166.jpg", alt:   "Art IMG_5166" },
        {type:"image", src:"Image/IMG_5167.jpg", alt:   "Art IMG_5167" },
        {type:"image", src:"Image/IMG_5168.jpg", alt:   "Art IMG_5168" },
        {type:"image", src:"Image/IMG_5169.jpg", alt:   "Art IMG_5169" },
        {type:"image", src:"Image/IMG_5170.jpg", alt:   "Art IMG_5170" },
        {type:"image", src:"Image/IMG_5171.jpg", alt:   "Art IMG_5171" },
        {type:"image", src:"Image/IMG_5172.jpg", alt:   "Art IMG_5172" },
        {type:"image", src:"Image/IMG_5173.jpg", alt:   "Art IMG_5173" },
        {type:"image", src:"Image/IMG_5174.jpg", alt:   "Art IMG_5174" },
        {type:"image", src:"Image/IMG_5175.jpg", alt:   "Art IMG_5175" },
        {type:"image", src:"Image/IMG_5176.jpg", alt:   "Art IMG_5176" },
        {type:"image", src:"Image/IMG_5177.jpg", alt:   "Art IMG_5177" },
        {type:"image", src:"Image/IMG_5178.jpg", alt:   "Art IMG_5178" },
        {type:"image", src:"Image/IMG_5179.jpg", alt:   "Art IMG_5179" },
        {type:"image", src:"Image/IMG_5180.jpg", alt:   "Art IMG_5180" },
        {type:"image", src:"Image/IMG_5181.jpg", alt:   "Art IMG_5181" },
        {type:"image", src:"Image/IMG_5182.jpg", alt:   "Art IMG_5182" },
        {type:"image", src:"Image/IMG_5183.jpg", alt:   "Art IMG_5183" },
        {type:"image", src:"Image/IMG_5184.jpg", alt:   "Art IMG_5184" },
        {type:"image", src:"Image/IMG_5185.jpg", alt:   "Art IMG_5185" },
        {type:"image", src:"Image/IMG_5186.jpg", alt:   "Art IMG_5186" },
        {type:"image", src:"Image/IMG_5187.jpg", alt:   "Art IMG_5187" },
        {type:"image", src:"Image/IMG_5188.jpg", alt:   "Art IMG_5188" },
        {type:"image", src:"Image/IMG_5195.jpg", alt:   "Art IMG_5195" },
        {type:"image", src:"Image/IMG_5196.jpg", alt:   "Art IMG_5196" },
        {type:"image", src:"Image/IMG_5197.jpg", alt:   "Art IMG_5197" },
        {type:"image", src:"Image/IMG_5198.jpg", alt:   "Art IMG_5198" },
        {type:"image", src:"Image/IMG_5199.jpg", alt:   "Art IMG_5199" },
        {type:"image", src:"Image/IMG_5200.jpg", alt:   "Art IMG_5200" },
        {type:"image", src:"Image/IMG_5201.jpg", alt:   "Art IMG_5201" },
        {type:"image", src:"Image/IMG_5202.jpg", alt:   "Art IMG_5202" },
        {type:"image", src:"Image/IMG_5203.jpg", alt:   "Art IMG_5203" },
        {type:"image", src:"Image/IMG_5204.jpg", alt:   "Art IMG_5204" },
        {type:"image", src:"Image/IMG_5205.jpg", alt:   "Art IMG_5205" },
        {type:"image", src:"Image/IMG_5206.jpg", alt:   "Art IMG_5206" },
        {type:"image", src:"Image/IMG_5207.jpg", alt:   "Art IMG_5207" },
        {type:"image", src:"Image/IMG_5208.jpg", alt:   "Art IMG_5208" },
        {type:"image", src:"Image/IMG_5209.jpg", alt:   "Art IMG_5209" },
        {type:"image", src:"Image/IMG_5210.jpg", alt:   "Art IMG_5210" },
        {type:"image", src:"Image/IMG_5211.jpg", alt:   "Art IMG_5211" },
        {type:"image", src:"Image/IMG_5212.jpg", alt:   "Art IMG_5212" },
        {type:"image", src:"Image/IMG_5213.jpg", alt:   "Art IMG_5213" },
        {type:"image", src:"Image/IMG_5214.jpg", alt:   "Art IMG_5214" },
        {type:"image", src:"Image/IMG_5215.jpg", alt:   "Art IMG_5215" },
        {type:"image", src:"Image/IMG_5216.jpg", alt:   "Art IMG_5216" },
        {type:"image", src:"Image/IMG_5217.jpg", alt:   "Art IMG_5217" },
        {type:"image", src:"Image/IMG_5218.jpg", alt:   "Art IMG_5218" },
        {type:"image", src:"Image/IMG_5219.jpg", alt:   "Art IMG_5219" },
        {type:"image", src:"Image/IMG_5220.jpg", alt:   "Art IMG_5220" },
        {type:"image", src:"Image/IMG_5221.jpg", alt:   "Art IMG_5221" },
        {type:"image", src:"Image/IMG_5222.jpg", alt:   "Art IMG_5222" },
        {type:"image", src:"Image/IMG_5223.jpg", alt:   "Art IMG_5223" },
        {type:"image", src:"Image/IMG_5224.jpg", alt:   "Art IMG_5224" },
        {type:"image", src:"Image/IMG_5225.jpg", alt:   "Art IMG_5225" },
        {type:"image", src:"Image/IMG_5226.jpg", alt:   "Art IMG_5226" },
        {type:"image", src:"Image/IMG_5227.jpg", alt:   "Art IMG_5227" },
        {type:"image", src:"Image/IMG_5228.jpg", alt:   "Art IMG_5228" },
        {type:"image", src:"Image/IMG_5229.jpg", alt:   "Art IMG_5229" },
        {type:"image", src:"Image/IMG_5230.jpg", alt:   "Art IMG_5230" },
        {type:"image", src:"Image/IMG_5231.jpg", alt:   "Art IMG_5231" },
        {type:"image", src:"Image/IMG_5232.jpg", alt:   "Art IMG_5232" },
        {type:"image", src:"Image/IMG_5233.jpg", alt:   "Art IMG_5233" },
        {type:"image", src:"Image/IMG_5234.jpg", alt:   "Art IMG_5234" },
        {type:"image", src:"Image/IMG_5235.jpg", alt:   "Art IMG_5235" },
        {type:"image", src:"Image/IMG_5236.jpg", alt:   "Art IMG_5236" },
        {type:"image", src:"Image/IMG_5237.jpg", alt:   "Art IMG_5237" },
        {type:"image", src:"Image/IMG_5238.jpg", alt:   "Art IMG_5238" },
        {type:"image", src:"Image/IMG_5239.jpg", alt:   "Art IMG_5239" },
        {type:"image", src:"Image/IMG_5240.jpg", alt:   "Art IMG_5240" },
        {type:"image", src:"Image/IMG_5241.jpg", alt:   "Art IMG_5241" },
        {type:"image", src:"Image/IMG_5242.jpg", alt:   "Art IMG_5242" },
        {type:"image", src:"Image/IMG_5243.jpg", alt:   "Art IMG_5243" },
        {type:"image", src:"Image/IMG_5244.jpg", alt:   "Art IMG_5244" },
        {type:"image", src:"Image/IMG_5245.jpg", alt:   "Art IMG_5245" },
        {type:"image", src:"Image/IMG_5246.jpg", alt:   "Art IMG_5246" },
        {type:"image", src:"Image/IMG_5247.jpg", alt:   "Art IMG_5247" },
        {type:"image", src:"Image/IMG_5248.jpg", alt:   "Art IMG_5248" },
        {type:"image", src:"Image/IMG_5249.jpg", alt:   "Art IMG_5249" },
        {type:"image", src:"Image/IMG_5250.jpg", alt:   "Art IMG_5250" },
        {type:"image", src:"Image/IMG_5251.jpg", alt:   "Art IMG_5251" },
        {type:"image", src:"Image/IMG_5252.jpg", alt:   "Art IMG_5252" },
        {type:"image", src:"Image/IMG_5253.jpg", alt:   "Art IMG_5253" },
        {type:"image", src:"Image/IMG_5254.jpg", alt:   "Art IMG_5254" },
        {type:"image", src:"Image/IMG_5255.jpg", alt:   "Art IMG_5255" },
        {type:"image", src:"Image/IMG_5256.jpg", alt:   "Art IMG_5256" },
        {type:"image", src:"Image/IMG_5257.jpg", alt:   "Art IMG_5257" },
        {type:"image", src:"Image/IMG_5258.jpg", alt:   "Art IMG_5258" },
        {type:"image", src:"Image/IMG_5259.jpg", alt:   "Art IMG_5259" },
        {type:"image", src:"Image/IMG_5260.jpg", alt:   "Art IMG_5260" },
        {type:"image", src:"Image/IMG_5261.jpg", alt:   "Art IMG_5261" },
        {type:"image", src:"Image/IMG_5262.jpg", alt:   "Art IMG_5262" },
        {type:"image", src:"Image/IMG_5263.jpg", alt:   "Art IMG_5263" },
        {type:"image", src:"Image/IMG_5264.jpg", alt:   "Art IMG_5264" },
        {type:"image", src:"Image/IMG_5265.jpg", alt:   "Art IMG_5265" },
        {type:"image", src:"Image/IMG_5266.jpg", alt:   "Art IMG_5266" },
        {type:"image", src:"Image/IMG_5267.jpg", alt:   "Art IMG_5267" },
        {type:"image", src:"Image/IMG_5268.jpg", alt:   "Art IMG_5268" },
        {type:"image", src:"Image/IMG_5269.jpg", alt:   "Art IMG_5269" },
        {type:"image", src:"Image/IMG_5270.jpg", alt:   "Art IMG_5270" },
        {type:"image", src:"Image/IMG_5271.jpg", alt:   "Art IMG_5271" },
        {type:"image", src:"Image/IMG_5272.jpg", alt:   "Art IMG_5272" },
        {type:"image", src:"Image/IMG_5273.jpg", alt:   "Art IMG_5273" },
        {type:"image", src:"Image/IMG_5274.jpg", alt:   "Art IMG_5274" },
        {type:"image", src:"Image/IMG_5275.jpg", alt:   "Art IMG_5275" },
        {type:"image", src:"Image/IMG_5276.jpg", alt:   "Art IMG_5276" },
        {type:"image", src:"Image/IMG_5277.jpg", alt:   "Art IMG_5277" },
        {type:"image", src:"Image/IMG_5278.jpg", alt:   "Art IMG_5278" },
        {type:"image", src:"Image/IMG_5279.jpg", alt:   "Art IMG_5279" },
        {type:"image", src:"Image/IMG_5280.jpg", alt:   "Art IMG_5280" },
        {type:"image", src:"Image/IMG_5281.jpg", alt:   "Art IMG_5281" },
        {type:"image", src:"Image/IMG_5282.jpg", alt:   "Art IMG_5282" },
        {type:"image", src:"Image/IMG_5283.jpg", alt:   "Art IMG_5283" },
        {type:"image", src:"Image/IMG_5284.jpg", alt:   "Art IMG_5284" },
        {type:"image", src:"Image/IMG_5285.jpg", alt:   "Art IMG_5285" },
        {type:"image", src:"Image/IMG_5286.jpg", alt:   "Art IMG_5286" },
        {type:"image", src:"Image/IMG_5287.jpg", alt:   "Art IMG_5287" },
        {type:"image", src:"Image/IMG_5288.jpg", alt:   "Art IMG_5288" },
        {type:"image", src:"Image/IMG_5289.jpg", alt:   "Art IMG_5289" },
        {type:"image", src:"Image/IMG_5290.jpg", alt:   "Art IMG_5290" },
        {type:"image", src:"Image/IMG_5291.jpg", alt:   "Art IMG_5291" },
        {type:"image", src:"Image/IMG_5292.jpg", alt:   "Art IMG_5292" },
        {type:"image", src:"Image/IMG_5293.jpg", alt:   "Art IMG_5293" },
        {type:"image", src:"Image/IMG_5294.jpg", alt:   "Art IMG_5294" },
        {type:"image", src:"Image/IMG_5295.jpg", alt:   "Art IMG_5295" },
        {type:"image", src:"Image/IMG_5296.jpg", alt:   "Art IMG_5296" },
        {type:"image", src:"Image/IMG_5297.jpg", alt:   "Art IMG_5297" },
        {type:"image", src:"Image/IMG_5298.jpg", alt:   "Art IMG_5298" },
        {type:"image", src:"Image/IMG_5299.jpg", alt:   "Art IMG_5299" },
        {type:"image", src:"Image/IMG_5300.jpg", alt:   "Art IMG_5300" },
        {type:"image", src:"Image/IMG_5301.jpg", alt:   "Art IMG_5301" },
        {type:"image", src:"Image/IMG_5302.jpg", alt:   "Art IMG_5302" },
        {type:"image", src:"Image/IMG_5303.jpg", alt:   "Art IMG_5303" },
        {type:"image", src:"Image/IMG_5304.jpg", alt:   "Art IMG_5304" },
        {type:"image", src:"Image/IMG_5305.jpg", alt:   "Art IMG_5305" },
        {type:"image", src:"Image/IMG_5306.jpg", alt:   "Art IMG_5306" },
        {type:"image", src:"Image/IMG_5307.jpg", alt:   "Art IMG_5307" },
        {type:"image", src:"Image/IMG_5308.jpg", alt:   "Art IMG_5308" },
        {type:"image", src:"Image/IMG_5309.jpg", alt:   "Art IMG_5309" },
        {type:"image", src:"Image/IMG_5310.jpg", alt:   "Art IMG_5310" },
        {type:"image", src:"Image/IMG_5311.jpg", alt:   "Art IMG_5311" },
        {type:"image", src:"Image/IMG_5312.jpg", alt:   "Art IMG_5312" },
        {type:"image", src:"Image/IMG_5313.jpg", alt:   "Art IMG_5313" },
        {type:"image", src:"Image/IMG_5314.jpg", alt:   "Art IMG_5314" },
        {type:"image", src:"Image/IMG_5315.jpg", alt:   "Art IMG_5315" },
        {type:"image", src:"Image/IMG_5316.jpg", alt:   "Art IMG_5316" },
        {type:"image", src:"Image/IMG_5317.jpg", alt:   "Art IMG_5317" },
        {type:"image", src:"Image/IMG_5318.jpg", alt:   "Art IMG_5318" },
        {type:"image", src:"Image/IMG_5319.jpg", alt:   "Art IMG_5319" },
        {type:"image", src:"Image/IMG_5320.jpg", alt:   "Art IMG_5320" },
        {type:"image", src:"Image/IMG_5321.jpg", alt:   "Art IMG_5321" },
        {type:"image", src:"Image/IMG_5322.jpg", alt:   "Art IMG_5322" },
        {type:"image", src:"Image/IMG_5323.jpg", alt:   "Art IMG_5323" },
        {type:"image", src:"Image/IMG_5324.jpg", alt:   "Art IMG_5324" },
        {type:"image", src:"Image/IMG_5325.jpg", alt:   "Art IMG_5325" },
        {type:"image", src:"Image/IMG_5326.jpg", alt:   "Art IMG_5326" },
        {type:"image", src:"Image/IMG_5327.jpg", alt:   "Art IMG_5327" },
        {type:"image", src:"Image/IMG_5328.jpg", alt:   "Art IMG_5328" },
        {type:"image", src:"Image/IMG_5329.jpg", alt:   "Art IMG_5329" },
        {type:"image", src:"Image/IMG_5330.jpg", alt:   "Art IMG_5330" },
        {type:"image", src:"Image/IMG_5331.jpg", alt:   "Art IMG_5331" },
        {type:"image", src:"Image/IMG_5332.jpg", alt:   "Art IMG_5332" },
        {type:"image", src:"Image/IMG_5333.jpg", alt:   "Art IMG_5333" },
        {type:"image", src:"Image/IMG_5334.jpg", alt:   "Art IMG_5334" },
        {type:"image", src:"Image/IMG_5335.jpg", alt:   "Art IMG_5335" },
        {type:"image", src:"Image/IMG_5336.jpg", alt:   "Art IMG_5336" },
        {type:"image", src:"Image/IMG_5337.jpg", alt:   "Art IMG_5337" },
        {type:"image", src:"Image/IMG_5338.jpg", alt:   "Art IMG_5338" },
        {type:"image", src:"Image/IMG_5339.jpg", alt:   "Art IMG_5339" },
        {type:"image", src:"Image/IMG_5340.jpg", alt:   "Art IMG_5340" },
        {type:"image", src:"Image/IMG_5341.jpg", alt:   "Art IMG_5341" },
        {type:"image", src:"Image/IMG_5342.jpg", alt:   "Art IMG_5342" },
        {type:"image", src:"Image/IMG_5343.jpg", alt:   "Art IMG_5343" },
        {type:"image", src:"Image/IMG_5344.jpg", alt:   "Art IMG_5344" },
        {type:"image", src:"Image/IMG_5345.jpg", alt:   "Art IMG_5345" },
        {type:"image", src:"Image/IMG_5346.jpg", alt:   "Art IMG_5346" },
        {type:"image", src:"Image/IMG_5347.jpg", alt:   "Art IMG_5347" },
        {type:"image", src:"Image/IMG_5348.jpg", alt:   "Art IMG_5348" },
        {type:"image", src:"Image/IMG_5349.jpg", alt:   "Art IMG_5349" },
        {type:"image", src:"Image/IMG_5350.jpg", alt:   "Art IMG_5350" },
        {type:"image", src:"Image/IMG_5351.jpg", alt:   "Art IMG_5351" },
        {type:"image", src:"Image/IMG_5352.jpg", alt:   "Art IMG_5352" },
        {type:"image", src:"Image/IMG_5353.jpg", alt:   "Art IMG_5353" },
        {type:"image", src:"Image/IMG_5354.jpg", alt:   "Art IMG_5354" },
        {type:"image", src:"Image/IMG_5355.jpg", alt:   "Art IMG_5355" },
        {type:"image", src:"Image/IMG_5356.jpg", alt:   "Art IMG_5356" },
        {type:"image", src:"Image/IMG_5357.jpg", alt:   "Art IMG_5357" },
        {type:"image", src:"Image/IMG_5358.jpg", alt:   "Art IMG_5358" },
        {type:"image", src:"Image/IMG_5359.jpg", alt:   "Art IMG_5359" },
        {type:"image", src:"Image/IMG_5360.jpg", alt:   "Art IMG_5360" },
        {type:"image", src:"Image/IMG_5361.jpg", alt:   "Art IMG_5361" },
        {type:"image", src:"Image/IMG_5362.jpg", alt:   "Art IMG_5362" },
        {type:"image", src:"Image/IMG_5363.jpg", alt:   "Art IMG_5363" },
        {type:"image", src:"Image/IMG_5364.jpg", alt:   "Art IMG_5364" },
        {type:"image", src:"Image/IMG_5365.jpg", alt:   "Art IMG_5365" },
        {type:"image", src:"Image/IMG_5366.jpg", alt:   "Art IMG_5366" },
        {type:"image", src:"Image/IMG_5367.jpg", alt:   "Art IMG_5367" },
        {type:"image", src:"Image/IMG_5368.jpg", alt:   "Art IMG_5368" },
        {type:"image", src:"Image/IMG_5369.jpg", alt:   "Art IMG_5369" },
        {type:"image", src:"Image/IMG_5370.jpg", alt:   "Art IMG_5370" },
        {type:"image", src:"Image/IMG_5371.jpg", alt:   "Art IMG_5371" },
        {type:"image", src:"Image/IMG_5372.jpg", alt:   "Art IMG_5372" },
        {type:"image", src:"Image/IMG_5373.jpg", alt:   "Art IMG_5373" },
        {type:"image", src:"Image/IMG_5374.jpg", alt:   "Art IMG_5374" },
        {type:"image", src:"Image/IMG_5375.jpg", alt:   "Art IMG_5375" },
        {type:"image", src:"Image/IMG_5376.jpg", alt:   "Art IMG_5376" },
        {type:"image", src:"Image/IMG_5377.jpg", alt:   "Art IMG_5377" },
        {type:"image", src:"Image/IMG_5378.jpg", alt:   "Art IMG_5378" },
        {type:"image", src:"Image/IMG_5379.jpg", alt:   "Art IMG_5379" },
        {type:"image", src:"Image/IMG_5380.jpg", alt:   "Art IMG_5380" },
        {type:"image", src:"Image/IMG_5381.jpg", alt:   "Art IMG_5381" },
        {type:"image", src:"Image/IMG_5382.jpg", alt:   "Art IMG_5382" },
        {type:"image", src:"Image/IMG_5383.jpg", alt:   "Art IMG_5383" },
        {type:"image", src:"Image/IMG_5384.jpg", alt:   "Art IMG_5384" },
        {type:"image", src:"Image/IMG_5385.jpg", alt:   "Art IMG_5385" },
        {type:"image", src:"Image/IMG_5386.jpg", alt:   "Art IMG_5386" },
        {type:"image", src:"Image/IMG_5387.jpg", alt:   "Art IMG_5387" },
        {type:"image", src:"Image/IMG_5388.jpg", alt:   "Art IMG_5388" },
        {type:"image", src:"Image/IMG_5389.jpg", alt:   "Art IMG_5389" },
        {type:"image", src:"Image/IMG_5390.jpg", alt:   "Art IMG_5390" },
        {type:"image", src:"Image/IMG_5391.jpg", alt:   "Art IMG_5391" },
        {type:"image", src:"Image/IMG_5392.jpg", alt:   "Art IMG_5392" },
        {type:"image", src:"Image/IMG_5393.jpg", alt:   "Art IMG_5393" },
        {type:"image", src:"Image/IMG_5394.jpg", alt:   "Art IMG_5394" },
        {type:"image", src:"Image/IMG_5395.jpg", alt:   "Art IMG_5395" },
        {type:"image", src:"Image/IMG_5396.jpg", alt:   "Art IMG_5396" },
        {type:"image", src:"Image/IMG_5397.jpg", alt:   "Art IMG_5397" },
        {type:"image", src:"Image/IMG_5398.jpg", alt:   "Art IMG_5398" },
        {type:"image", src:"Image/IMG_5399.jpg", alt:   "Art IMG_5399" },
        {type:"image", src:"Image/IMG_5400.jpg", alt:   "Art IMG_5400" },
        {type:"image", src:"Image/IMG_5401.jpg", alt:   "Art IMG_5401" },
        {type:"image", src:"Image/IMG_5402.jpg", alt:   "Art IMG_5402" },
        {type:"image", src:"Image/IMG_5403.jpg", alt:   "Art IMG_5403" },
        {type:"image", src:"Image/IMG_5404.jpg", alt:   "Art IMG_5404" },
    // ចង់ថែមថ្មី គ្រាន់តែ Copy ជួរខាងលើមកដាក់បន្តបន្ទាប់នៅទីនេះ...
];